export const safeApiUrls: Record<string, string> = {
  mainnet: 'https://safe-transaction-mainnet.safe.global',
  arbitrum: 'https://safe-transaction-arbitrum.safe.global',
  aurora: 'https://safe-transaction-aurora.safe.global',
  avalanche: 'https://safe-transaction-avalanche.safe.global',
  base: 'https://safe-transaction-base.safe.global',
  boba: 'https://safe-transaction.mainnet.boba.network',
  bsc: 'https://safe-transaction-bsc.safe.global',
  celo: 'https://safe-transaction-celo.safe.global',
  fantom: 'https://safe-txservice.fantom.network',
  fuse: 'https://transaction-fuse.safe.fuse.io/',
  gnosis: 'https://safe-transaction-gnosis-chain.safe.global',
  linea: 'https://transaction.safe.linea.build',
  // metis
  mode: 'https://transaction-mode.safe.optimism.io',
  moonbeam: 'https://transaction.multisig.moonbeam.network',
  moonriver: 'https://transaction.moonriver.multisig.moonbeam.network',
  optimism: 'https://safe-transaction-optimism.safe.global',
  polygon: 'https://safe-transaction-polygon.safe.global',
  polygonzkevm: 'https://safe-transaction-zkevm.safe.global',
  scroll: 'https://transaction.safe.scroll.xyz',
  zksync: 'https://safe-transaction-zksync.safe.global',
}
