export const safeApiUrls: Record<string, string> = {
  mainnet: 'https://safe-transaction-mainnet.safe.global/api',
  arbitrum: 'https://safe-transaction-arbitrum.safe.global/api',
  aurora: 'https://safe-transaction-aurora.safe.global/api',
  avalanche: 'https://safe-transaction-avalanche.safe.global/api',
  base: 'https://safe-transaction-base.safe.global/api',
  boba: 'https://safe-transaction.mainnet.boba.network/api',
  bsc: 'https://safe-transaction-bsc.safe.global/api',
  celo: 'https://safe-transaction-celo.safe.global/api',
  fantom: 'https://safe-txservice.fantom.network/api',
  fuse: 'https://transaction-fuse.safe.fuse.io//api',
  gnosis: 'https://safe-transaction-gnosis-chain.safe.global/api',
  linea: 'https://transaction.safe.linea.build/api',
  // metis
  mode: 'https://transaction-mode.safe.optimism.io/api',
  moonbeam: 'https://transaction.multisig.moonbeam.network/api',
  moonriver: 'https://transaction.moonriver.multisig.moonbeam.network/api',
  optimism: 'https://safe-transaction-optimism.safe.global/api',
  polygon: 'https://safe-transaction-polygon.safe.global/api',
  polygonzkevm: 'https://safe-transaction-zkevm.safe.global/api',
  scroll: 'https://transaction.safe.scroll.xyz/api',
  zksync: 'https://safe-transaction-zksync.safe.global/api',
}
