# - Protect "AuditCompleted" Label
# - makes sure that the label "AuditCompleted" can only be assigned by a Github action and not by a human actor
# - will undo any unauthorized change of this label
# - will fail if it runs into an error, otherwise pass

name: Protect "AuditCompleted" Label

on:
  pull_request_target: #### << needs to be changed to 'pull_request' to activate it
    types: [labeled, unlabeled]

jobs:
  protect_audit_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Event Payload
        run: |
          if [[ "${{ github.actor }}" == "github-actions" ]]; then
            echo "This action was triggered by another GitHub Action."
          else
            echo "This action was triggered by a user: ${{ github.actor }}."
          fi
          echo "${{ github.event }}"

      - name: Check if "AuditCompleted" label was modified
        env:
          GITHUB_TOKEN: ${{ secrets.LIFI_GIT_ACTIONS_TOKEN }}
          GH_PAT: ${{ secrets.LIFI_GIT_ACTIONS_TOKEN }}
        run: |
          # The label being monitored
          TARGET_LABEL="AuditCompleted"

          # Check if the event was triggered by any other github action
          if [[ "${{ github.actor }}" != "lifiGitActions" ]]; then #### TODO: REPLACE WITH GITHUB_ACTIONS_PAT and USERNAME <<<<<-----------
            echo "This event was triggered by ${{ github.actor }}. Checking label..."

            # Determine if the label was added or removed
            ACTION_TYPE="none"
            if [[ "${{ github.event.action }}" == "labeled" && "${{ github.event.label.name }}" == "$TARGET_LABEL" ]]; then
              ACTION_TYPE="added"
            elif [[ "${{ github.event.action }}" == "unlabeled" && "${{ github.event.label.name }}" == "$TARGET_LABEL" ]]; then
              ACTION_TYPE="removed"
            fi

            # Revert the label change if necessary
            if [[ "$ACTION_TYPE" != "none" ]]; then
              echo -e "\033[31mUnauthorized modification of '$TARGET_LABEL' by ${{ github.actor }}. Reverting change...\033[0m"

              ##### remove or re-add label, depending on the case
              if [[ "$ACTION_TYPE" == "added" ]]; then
                # Remove the unauthorized label addition
                gh pr edit ${{ github.event.pull_request.number }} --remove-label "$TARGET_LABEL"
              elif [[ "$ACTION_TYPE" == "removed" ]]; then
                # Re-add the unauthorized label removal
                 gh pr edit ${{ github.event.pull_request.number }} --add-label "$TARGET_LABEL"
              fi

              # make sure that the label change was undone
              CURRENT_LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
              if [[ "$ACTION_TYPE" == "added" && "$CURRENT_LABELS" == *"$TARGET_LABEL"* ]]; then
                echo -e "\033[31Failed to remove the unauthorized 'AuditCompleted' label.\033[0m"
                exit 1
                elif [[ "$ACTION_TYPE" == "removed" && "$CURRENT_LABELS" != *"$TARGET_LABEL"* ]]; then
                echo -e "\033[31Failed to re-add the 'AuditCompleted' label.\033[0m"
                exit 1
              fi

              echo -e "\033[32Unauthorized label modification was successfully prevented and undone.\033[0m"
            else
              echo -e "\033[32mNo unauthorized modifications detected.\033[0m"
            fi
          else
            echo -e "\033[32mLabel change initiated by GitHub Action. No checks required.\033[0m"
          fi
