#!/usr/bin/env bun

/**
 * Purpose:
 *   Guard against the audit/knowledge/ corpus drifting out of sync with
 *   audit/auditLog.json. When a new audit lands but /extract-audit-knowledge
 *   was not invoked, the LF-NNN corpus consumed by the security-review
 *   pipeline (EXP-483) is silently incomplete — future PR reviews would
 *   miss past findings the corpus was supposed to surface.
 *
 *   This script reads:
 *     - audit/auditLog.json          (canonical list of audits)
 *     - audit/knowledge/findings.json (the corpus generated by EXP-478/479)
 *   and exits non-zero if any audit in the log has no findings recorded
 *   in the corpus.
 *
 * Usage:
 *   # Absolute check (local / informational — reports total drift):
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts --json
 *
 *   # PR check (CI mode — only fails on audits added by this PR):
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts \
 *     --new-audits audit20260520,audit20260521
 *
 * Exit codes:
 *   0  All NEW audits have corpus entries (CI mode), OR no drift at all (absolute mode)
 *   1  Drift detected on audits this PR introduced (CI mode), OR any drift (absolute mode)
 *   2  Input files unreadable or malformed
 *
 * Related:
 *   .agents/commands/add-audit.md           — entry point for new audits
 *   .agents/commands/extract-audit-knowledge.md — fills the corpus
 *   .github/workflows/audit-knowledge-coverage.yml — CI enforcement
 */

import fs from 'fs'
import path from 'path'

const REPO_ROOT = path.resolve(__dirname, '..', '..')
const AUDIT_LOG = path.join(REPO_ROOT, 'audit', 'auditLog.json')
const FINDINGS = path.join(REPO_ROOT, 'audit', 'knowledge', 'findings.json')

type AuditLogEntry = {
  auditCompletedOn: string
  auditedBy: string
  auditorGitHandle?: string
  auditReportPath: string
  auditCommitHash?: string
}

type AuditLog = {
  audits: Record<string, AuditLogEntry>
}

type StatusHistoryEntry = {
  audit_id: string
  source_label: string
  status: string
}

type Finding = {
  id: string
  status_history: StatusHistoryEntry[]
}

type FindingsCorpus = {
  schema_version: string
  findings: Record<string, Finding>
}

function readJson<T>(p: string): T {
  const raw = fs.readFileSync(p, 'utf8')
  return JSON.parse(raw) as T
}

function parseNewAudits(): string[] | null {
  const flagIdx = process.argv.indexOf('--new-audits')
  if (flagIdx === -1) return null
  const raw = process.argv[flagIdx + 1] ?? ''
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

function main(): void {
  const wantJson = process.argv.includes('--json')
  const newAudits = parseNewAudits()
  const prMode = newAudits !== null

  let log: AuditLog
  let corpus: FindingsCorpus
  try {
    log = readJson<AuditLog>(AUDIT_LOG)
    corpus = readJson<FindingsCorpus>(FINDINGS)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(`error: could not read coverage inputs: ${msg}`)
    process.exit(2)
  }

  const logIds = new Set(Object.keys(log.audits ?? {}))
  const corpusIds = new Set<string>()
  for (const f of Object.values(corpus.findings ?? {})) {
    for (const h of f.status_history ?? []) {
      if (h.audit_id) corpusIds.add(h.audit_id)
    }
  }

  // In PR mode, the relevant set is only the IDs this PR added — pre-existing
  // gaps are EXP-479 backfill work, not this PR's responsibility.
  const scoped = prMode ? new Set(newAudits) : logIds
  const missing = [...scoped].filter((id) => !corpusIds.has(id)).sort()
  const orphaned = [...corpusIds].filter((id) => !logIds.has(id)).sort()
  const preexistingDrift = prMode
    ? [...logIds].filter((id) => !corpusIds.has(id) && !scoped.has(id)).length
    : 0

  if (wantJson) {
    process.stdout.write(
      `${JSON.stringify(
        {
          mode: prMode ? 'pr' : 'absolute',
          log_audits: logIds.size,
          corpus_audits: corpusIds.size,
          scoped_to: prMode ? newAudits : null,
          missing_from_corpus: missing,
          orphaned_in_corpus: orphaned,
          preexisting_drift: preexistingDrift,
          ok: missing.length === 0,
        },
        null,
        2
      )}\n`
    )
  } else {
    const header = prMode
      ? `mode:                 pr (--new-audits=${
          newAudits.join(',') || '(none)'
        })\n`
      : 'mode:                 absolute\n'
    console.log(
      header +
        `audits in log:        ${logIds.size}\n` +
        `audits in corpus:     ${corpusIds.size}\n` +
        `missing (scoped):     ${missing.length}\n` +
        `orphaned in corpus:   ${orphaned.length}` +
        (prMode ? `\npre-existing drift:   ${preexistingDrift}` : '')
    )
    if (orphaned.length > 0) {
      console.log(
        '\nwarning: corpus references audits that are NOT in auditLog.json:'
      )
      for (const id of orphaned) console.log(`  ${id}`)
      console.log(
        'Likely cause: audit was removed from auditLog.json after extraction. ' +
          'Run /extract-audit-knowledge to refresh, or remove the stale findings ' +
          'from audit/knowledge/findings.json by hand.'
      )
    }
  }

  if (missing.length === 0) {
    if (!wantJson) {
      if (prMode) {
        console.log(
          `\nOK: all ${newAudits.length} audit(s) added by this PR have corpus entries.`
        )
        if (preexistingDrift > 0) {
          console.log(
            `\nnote: ${preexistingDrift} pre-existing audits in auditLog.json ` +
              `still lack corpus entries (EXP-479 backfill work; not this PR's ` +
              `responsibility — run without --new-audits to see the full list).`
          )
        }
      } else {
        console.log('\nOK: all audits in auditLog.json have corpus entries.')
      }
    }
    process.exit(0)
  }

  if (!wantJson) {
    console.error(
      prMode
        ? '\nerror: this PR adds audit(s) to auditLog.json without corpus entries:'
        : '\nerror: audit/knowledge/ corpus is missing entries for these audits:'
    )
    for (const id of missing) {
      const entry = log.audits[id]
      const pdf = entry?.auditReportPath ?? '(unknown PDF)'
      console.error(`  ${id}  →  ${pdf}`)
    }
    console.error(
      '\nFix: run /extract-audit-knowledge for each listed audit, ' +
        'then commit the updated audit/knowledge/ files alongside your PR.'
    )
    console.error(
      'See docs/security-review.md § "Audit-knowledge coverage" for details.'
    )
  }
  process.exit(1)
}

main()
