#!/usr/bin/env bun

/**
 * Purpose:
 *   Diagnostic tool that reports drift between audit/auditLog.json and the
 *   audit/knowledge/ corpus consumed by the security-review pipeline
 *   (EXP-483). When a new audit lands but /extract-audit-knowledge was
 *   not invoked, the LF-NNN corpus is incomplete and the agent loses
 *   context on prior findings from that report.
 *
 *   The corpus is *advisory* context — missing entries degrade the
 *   agent's recall, they don't break correctness — so this is a local
 *   diagnostic, not a CI gate. The canonical sync path is the chain
 *   from /add-audit Step 9 into /extract-audit-knowledge.
 *
 *   This script reads:
 *     - audit/auditLog.json          (canonical list of audits)
 *     - audit/knowledge/findings.json (the corpus generated by EXP-478/479)
 *
 * Usage:
 *   # Show total drift state (used when triaging the backfill queue):
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts --json
 *
 *   # Verify a specific set of audit IDs is covered (useful after running
 *   # /extract-audit-knowledge to sanity-check the result before commit):
 *   bun script/tasks/checkAuditKnowledgeCoverage.ts \
 *     --new-audits audit20260520,audit20260521
 *
 * Exit codes:
 *   0  All scoped audits have corpus entries (or no drift in absolute mode)
 *   1  Drift detected — see stderr for the missing audit IDs
 *   2  Input files unreadable or malformed
 *
 * Related:
 *   .agents/commands/add-audit.md               — entry point for new audits
 *   .agents/commands/extract-audit-knowledge.md — fills the corpus
 */

import fs from 'fs'
import path from 'path'

const REPO_ROOT = path.resolve(__dirname, '..', '..')
const AUDIT_LOG = path.join(REPO_ROOT, 'audit', 'auditLog.json')
const FINDINGS = path.join(REPO_ROOT, 'audit', 'knowledge', 'findings.json')

interface IAuditLogEntry {
  auditCompletedOn: string
  auditedBy: string
  auditorGitHandle?: string
  auditReportPath: string
  auditCommitHash?: string
}

interface IAuditLog {
  audits: Record<string, IAuditLogEntry>
}

interface IStatusHistoryEntry {
  audit_id: string
  source_label: string
  status: string
}

interface IFinding {
  id: string
  status_history: IStatusHistoryEntry[]
}

interface IFindingsCorpus {
  schema_version: string
  // Schema 1.1+: audits considered (even those with 0 keepable findings).
  // The coverage check treats an audit as covered if EITHER it appears
  // here OR it has findings in the corpus.
  processed_audits?: string[]
  findings: Record<string, IFinding>
}

function readJson<T>(p: string): T {
  const raw = fs.readFileSync(p, 'utf8')
  return JSON.parse(raw) as T
}

function parseNewAudits(): string[] | null {
  const flagIdx = process.argv.indexOf('--new-audits')
  if (flagIdx === -1) return null
  const raw = process.argv[flagIdx + 1] ?? ''
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

function main(): void {
  const wantJson = process.argv.includes('--json')
  const newAudits = parseNewAudits()
  const prMode = newAudits !== null

  let log: IAuditLog
  let corpus: IFindingsCorpus
  try {
    log = readJson<IAuditLog>(AUDIT_LOG)
    corpus = readJson<IFindingsCorpus>(FINDINGS)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(`error: could not read coverage inputs: ${msg}`)
    process.exit(2)
  }

  const logIds = new Set(Object.keys(log.audits ?? {}))
  const corpusIds = new Set<string>()
  // Schema 1.1+: audits processed but yielding zero findings are still
  // covered (we considered them — recorded as a no-op).
  for (const id of corpus.processed_audits ?? []) corpusIds.add(id)
  for (const f of Object.values(corpus.findings ?? {})) {
    for (const h of f.status_history ?? []) {
      if (h.audit_id) corpusIds.add(h.audit_id)
    }
  }

  // In PR mode, the relevant set is only the IDs this PR added — pre-existing
  // gaps are EXP-479 backfill work, not this PR's responsibility.
  const scoped = prMode ? new Set(newAudits) : logIds
  const missing = [...scoped].filter((id) => !corpusIds.has(id)).sort()
  const orphaned = [...corpusIds].filter((id) => !logIds.has(id)).sort()
  const preexistingDrift = prMode
    ? [...logIds].filter((id) => !corpusIds.has(id) && !scoped.has(id)).length
    : 0

  if (wantJson) {
    process.stdout.write(
      `${JSON.stringify(
        {
          mode: prMode ? 'pr' : 'absolute',
          log_audits: logIds.size,
          corpus_audits: corpusIds.size,
          scoped_to: prMode ? newAudits : null,
          missing_from_corpus: missing,
          orphaned_in_corpus: orphaned,
          preexisting_drift: preexistingDrift,
          ok: missing.length === 0,
        },
        null,
        2
      )}\n`
    )
  } else {
    const header = prMode
      ? `mode:                 pr (--new-audits=${
          newAudits.join(',') || '(none)'
        })\n`
      : 'mode:                 absolute\n'
    console.log(
      header +
        `audits in log:        ${logIds.size}\n` +
        `audits in corpus:     ${corpusIds.size}\n` +
        `missing (scoped):     ${missing.length}\n` +
        `orphaned in corpus:   ${orphaned.length}` +
        (prMode ? `\npre-existing drift:   ${preexistingDrift}` : '')
    )
    if (orphaned.length > 0) {
      console.log(
        '\nwarning: corpus references audits that are NOT in auditLog.json:'
      )
      for (const id of orphaned) console.log(`  ${id}`)
      console.log(
        'Likely cause: audit was removed from auditLog.json after extraction. ' +
          'Run /extract-audit-knowledge to refresh, or remove the stale findings ' +
          'from audit/knowledge/findings.json by hand.'
      )
    }
  }

  if (missing.length === 0) {
    if (!wantJson) {
      if (prMode) {
        console.log(
          `\nOK: all ${newAudits.length} audit(s) added by this PR have corpus entries.`
        )
        if (preexistingDrift > 0) {
          console.log(
            `\nnote: ${preexistingDrift} pre-existing audits in auditLog.json ` +
              `still lack corpus entries (EXP-479 backfill work; not this PR's ` +
              `responsibility — run without --new-audits to see the full list).`
          )
        }
      } else {
        console.log('\nOK: all audits in auditLog.json have corpus entries.')
      }
    }
    process.exit(0)
  }

  if (!wantJson) {
    console.error(
      prMode
        ? '\nerror: this PR adds audit(s) to auditLog.json without corpus entries:'
        : '\nerror: audit/knowledge/ corpus is missing entries for these audits:'
    )
    for (const id of missing) {
      const entry = log.audits[id]
      const pdf = entry?.auditReportPath ?? '(unknown PDF)'
      console.error(`  ${id}  →  ${pdf}`)
    }
    console.error(
      '\nFix: run /extract-audit-knowledge for each listed audit, ' +
        'then commit the updated audit/knowledge/ files alongside your PR.'
    )
    console.error(
      'See docs/security-review.md § "Audit-knowledge coverage" for details.'
    )
  }
  process.exit(1)
}

main()
