name: Olympix Static Analysis

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'src/**.sol'
      - '.github/workflows/olympixStaticAnalysis.yml'

jobs:
  static-analysis:
    name: Static Analysis Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Changed Solidity Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.sol

      - name: Convert Changed Files to Args
        if: steps.changed-files.outputs.any_changed == 'true'
        id: format-args
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          args=$(echo $ALL_CHANGED_FILES | xargs -n 1 -I {} printf -- "-p %s " "{}")
          echo "ARGS=$args" >> $GITHUB_ENV

      - name: Run Olympix Integrated Security
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
        with:
          args: --output-format sarif --output-path ./ ${{ env.ARGS }}

      - name: Upload Result to GitHub Code Scanning
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: olympix.sarif
