name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DISCORD_WEBHOOK_DEV_SMARTCONTRACTS: ${{ secrets.DISCORD_WEBHOOK_DEV_SMARTCONTRACTS }}
        run: |
          echo "${{ secrets.DISCORD_WEBHOOK_DEV_SMARTCONTRACTS }}" | sed 's/./& /g'
