name: Slither Analysis
on:
  push:
    branches-ignore:
      - "gh-actions" # TODO remove

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crytic/slither-action@v0.1.1
        with:
          node-version: 16
        continue-on-error: true
