name: Notify SmartContract channel when .env.example changes

on:
  push:
    branches:
      - main
    paths:
      - '.env.example'

permissions:
  contents: read # required to evaluate changed files and trigger based on path filters

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Reminder to Slack SC-general Channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_SC_GENERAL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Hey team, please update your .env file (see <https://github.com/lifinance/contracts/blob/main/.env.example|.env.example> for latest changes)"
