name: Version Check

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, edited, synchronize]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Fetch base branch
        run: git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Get list of modified files
        id: modified_files
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"

          # get all files modified by this PR
          FILES=$(git diff --name-only origin/${BASE_REF} HEAD)

          # make sure that modified files of this PR are available
          if [[ -z $FILES ]]; then
            echo "No files found. This should not happen. Please check the code of the Github action"
            exit 1
          fi

          # Initialize empty variables
          CONTRACTS=""

          # go through all file names and identify facet, periphery & diamond contracts (other contracts dont have versioning)
          while IFS= read -r FILE; do
            if echo "$FILE" | grep -E '^src/Facets/.*\.sol$'; then
              # facet found
              CONTRACTS="${CONTRACTS}${FILE}"$'\n'
            elif echo "$FILE" | grep -E '^src/Periphery/.*\.sol$'; then
              # periphery found
              CONTRACTS="${CONTRACTS}${FILE}"$'\n'
            elif echo "$FILE" | grep -E '^src/.*\.sol$'; then
              # diamond contract found
              CONTRACTS="${CONTRACTS}${FILE}"$'\n'
            fi
          done <<< "$FILES"

          # if none found, exit here as there is nothing to do
          if [[ -z "$CONTRACTS" ]]; then
            echo "No facets or periphery contracts found in files modified/added by this PR"
            exit 0
          fi

          # Write filenames to temporary files (using variables here was causing issues due to the file names)
          #echo "$FILES" > modified_files.txt
          echo "$CONTRACTS" > modified_contracts.txt
